// Wails Bridge client. The concrete bindings below are generated by
// `wails generate` into ../wailsjs and are NOT committed/built in this batch's
// environment (no Wails toolchain). The Go side is covered by in-process tests
// that use the same DTO surface (plugins/ui + tests/e2e_ui_p2_test.go).
//
// React -> Wails -> UI Host Adapter -> Application Query/Observation/Command.
import { EventsOn, EventsOff } from "../wailsjs/runtime/runtime";
import {
  UICollection,
  UIFile,
  UIObservation,
  UISource,
  UIListFilesRequest,
  UITriggerRequest,
} from "../models/types";

const App = (window as unknown as { go: { main: { App: Record<string, unknown> } } })
  .go.main.App;

async function call<T>(name: string, ...args: unknown[]): Promise<T> {
  const fn = App[name] as (...a: unknown[]) => Promise<T>;
  return await fn(...args);
}

export const api = {
  listSources: () => call<UISource[]>("ListSources"),
  listCollections: () => call<UICollection[]>("ListCollections"),
  listFiles: (req: UIListFilesRequest) => call<UIFile[]>("ListFiles", req),
  triggerCollection: (req: UITriggerRequest) =>
    call<void>("TriggerCollection", req),
};

export function onObservation(handler: (ev: UIObservation) => void): () => void {
  EventsOn("observation", handler);
  return () => EventsOff("observation");
}
